# Generated by Django 3.1.7 on 2021-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='web.Tag', verbose_name='Etiquetas'),
        ),
    ]
