# Generated by Django 3.1.7 on 2021-03-14 15:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('image', models.ImageField(upload_to=None, verbose_name='Imágen')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('visible', models.BooleanField(verbose_name='¿Público?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
